Shop/Controllers/AccountController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Shop.Domain.ViewModels.Account;
using Shop.Service.Interfaces;

namespace Shop.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService _accountService;
        
        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [HttpGet]
        public IActionResult Register() => View();

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _accountService.Register(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(response.Data as ClaimsIdentity));

                    return RedirectToAction("SuccessRegister");
                }
            }
            return View(model);
        }
        
        public IActionResult SuccessRegister() => View();


        [HttpGet]
        public IActionResult Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _accountService.Login(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(response.Data as ClaimsIdentity));

                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult ChangePassword() => View();
        
        [HttpPost]
        public async Task<IActionResult> ChangePassword(PasswordViewModel model)
        {
            ModelState.Remove("Name");
            if (ModelState.IsValid)
            {
                model.Name = User.Identity.Name;
                var response = await _accountService.ChangePassword(model);
                
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("Index", "Home");
                }

                ViewBag.Error = response.Description;
            }
            return View();
        }
        
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Shop/Controllers/BalanceController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Domain.Entity;
using Shop.Service.Interfaces;

namespace Shop.Controllers
{
    public class BalanceController : Controller
    {
        private readonly IBalanceService _balanceService;

        public BalanceController(IBalanceService balanceService)
        {
            _balanceService = balanceService;
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var userName = User.Identity.Name;
            var response = await _balanceService.Get(userName);
            return View(response.Data as User);
        }
    }
}

Shop/Controllers/BasketController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Domain.Entity;
using Shop.Service.Interfaces;

namespace Shop.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;

        public BasketController(IBasketService basketService)
        {
            _basketService = basketService;
        }
        
        public async Task<IActionResult> Add(int id)
        {
            await _basketService.Add(User.Identity.Name, id);
            return RedirectToAction("List");
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            await _basketService.Delete(User.Identity.Name, id);
            return RedirectToAction("List");
        }
        
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var user = User.Identity.Name;
            var response = await _basketService.Select(user);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data as List<Cloth>);
            }
            return View("Error");
        }
    }
}

Shop/Controllers/ClothController.cs
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Domain.Entity;
using Shop.Domain.ViewModels;
using Shop.Service.Interfaces;

namespace Shop.Controllers
{
    public class ClothController : Controller
    {
        private readonly IClothService _clothService;

        public ClothController(IClothService clothService)
        {
            _clothService = clothService;
        }

        [HttpGet("all")]
        public async Task<IActionResult> List(int parameter)
        {
            var response = await _clothService.GetClothes(parameter);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data as List<Cloth>);
            }
            return View("Error");
        }
        
        [HttpGet]
        public async Task<IActionResult> Get(int id)
        {
            var response = await _clothService.Get(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data as Cloth);   
            }
            return View("Error");
        }
        
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _clothService.Delete(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("List");
            }
            return View("Error");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Save(int id)
        {
            if (id == 0)
                return View();
            var response = await _clothService.Get(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data as ProductViewModel);   
            }
            return View("Error");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Save(ProductViewModel model)
        {
            ModelState.Remove("Id");
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    byte[] imageData = null;
                    if (model.Avatar != null)
                    {
                        using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
                        {
                            imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
                        }
                    }
                    
                    var response = await _clothService.Create(model, imageData);
                    return RedirectToAction("List");
                }
                else
                {
                    var response = await _clothService.Edit(model.Id, model);
                }
                return RedirectToAction("List");   
            }

            return View();
        }
    }
}

Shop/Controllers/GenderController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Service.Interfaces;

namespace Shop.Controllers
{
    public class GenderController : Controller
    {
        private readonly IClothService _clothService;

        public GenderController(IClothService clothService)
        {
            _clothService = clothService;
        }

        [HttpPost]
        public async Task<JsonResult> GetGenders(string term)
        {
            var types = await _clothService.GetGenders(term);
            return Json(types.Data);
        }
    }
}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() => View();
    }
}

Shop/Views/Basket/List.cshtml
@model List<Shop.Domain.Entity.Cloth>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div style="padding: 20px;"></div>
@if (Model == null || Model.Count == 0)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://images.wallpaperscraft.ru/image/single/planeta_komety_kosmos_163352_3840x2160.jpg" 
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body text-center">
                    <h5 class="card-title">Корзина пуста :(</h5>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 10px;"></div>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Index">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cloth" asp-action="List" asp-route-parameter="1">Мужские вещи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cloth" asp-action="List" asp-route-parameter="2">Женские вещи</a>
                </li>
            </ul>
        </div>
    </div>
    <div style="padding: 10px;"></div>
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Juicy Couture</h5>
                    <p class="card-text">
                        Всемирно известный американский бренд Juicy Couture может похвастаться миллионами поклонниц и поклонников по всему миру, и не меньшим количеством
                        противников продукции бренда. Почему так получилось? Давайте разберемся. Основателями бренда Juicy Couture стали две подруги Памела Скэйст-Леви
                        и Гела Нэш-Тейлор, которые в 1997-м году в Лос-Анджелесе создали свою первую коллекцию спортивных костюмов.
                    </p>
                    <a asp-controller="Balance" asp-action="Get" class="btn btn-primary">К балансу</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Michael Kors</h5>
                    <p class="card-text">
                        Michael Kors – это истинный вольный и либеральный американский модный бренд, являющийся собственностью одноименного дизайнера Майкла Корса (Michael Kors).
                        Главный офис бренда находится в Нью-Йорке и он активно занимается производством одежды, аксессуаров и парфюмерии класса "люкс".
                    </p>
                    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Главная</a>
                </div>
            </div>
        </div>
    </div>
}
else
{
 <div class="row">
     @for (int i = 0; i < Model.Count(); i++)
     {
         var cloth = Model[i];
         if (Model.Count() == 1)
         {
             <div class="col-sm-12">
                 <div class="card">
                     <div class="card-body">
                         <h5 class="card-title">@cloth?.Name</h5>
                         <p class="card-text">Описание: @cloth?.Description</p>
                         <p class="card-text">Цена: @cloth?.Price</p>
                         <a class="btn btn-danger" asp-controller="Basket" asp-action="Delete" asp-route-id="@cloth?.Id">Удалить</a>
                     </div>
                 </div>
             </div>
         }
         else
         {
             if (i % 2 == 0)
             {
                 <div class="col-sm-6">
                     <div class="card">
                         <div class="card-body">
                             <h5 class="card-title">@cloth?.Name</h5>
                              <p class="card-text">Описание: @cloth?.Description</p>
                              <p class="card-text">Цена: @cloth?.Price</p>
                              <a class="btn btn-danger" asp-controller="Basket" asp-action="Delete" asp-route-id="@cloth?.Id">Удалить</a>
                         </div>
                     </div>
                 </div>
             }
             else
             {
                 <div class="col-sm-6">
                     <div class="card">
                         <div class="card-body">
                             <h5 class="card-title">@cloth?.Name</h5>
                              <p class="card-text">Описание: @cloth?.Description</p>
                              <p class="card-text">Цена: @cloth?.Price</p>
                              <a class="btn btn-danger" asp-controller="Basket" asp-action="Delete" asp-route-id="@cloth?.Id">Удалить</a>
                         </div>
                     </div>
                 </div>
             }   
         }
     }
 </div>    
} 

Shop/Views/Cloth/Get.cshtml
@using Shop.Domain.Entity
@using Shop.Domain.Extensions
@model Cloth
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div style="padding: 10px;"></div>
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            @if (Model.Avatar != null)
            {
                <img class="img img-fluid" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Avatar))" />
            }
        </div>
        <div class="col-md-4">
            <div class="card-body">
                <h5 class="card-title text-center">@Model?.Name</h5>
                <p class="card-text"><b>Описание: </b>@Model?.Description</p>
                <p class="card-text"><b>Стоимость: </b>@Model?.Price ₽</p>
            </div>
        </div>
    </div>
</div>

<div style="padding: 30px;"></div>
<div class="card text-center">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                <a class="nav-link active" asp-controller="Home" asp-action="Index">Главная</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Cloth" asp-action="List" asp-route-parameter="1">Мужские вещи</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Cloth" asp-action="List" asp-route-parameter="2">Женские вещи</a>
            </li>
        </ul>
    </div>
</div>

Shop/Views/Cloth/List.cshtml
@model List<Shop.Domain.Entity.Cloth>
@{
    ViewBag.Title = "Список";
    Layout = "_Layout";
}

@{
    var cardSize = "col-md-4";

    /*if (Model.Count == 1)
        cardSize = "col-md-12";
    else if (Model.Count % 2 == 0)
        cardSize = "col-md-6";
    else cardSize = "col-md-4";*/
}

<style>
    .card-buttons-group {
        text-align: right;
        padding: 10px;
    }
</style>

<div style="padding: 10px;"></div>
@if (Model == null || Model.Count == 0)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://images.wallpaperscraft.ru/image/single/nogi_dzhinsy_krossovki_160153_1920x1080.jpg" 
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body text-center">
                    <h5 class="card-title">Список товаров пуст :(</h5>
                    <p class="card-text">
                        Список пополниться позже, не расстраивайтесь
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 30px;"></div>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Home" asp-action="Index">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cloth" asp-action="List" asp-route-parameter="1">Мужские вещи</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" asp-controller="Cloth" asp-action="List" asp-route-parameter="2">Женские вещи</a>
                </li>
            </ul>
        </div>
    </div>
}
else
{
    <div class="row">
        @for (int i = 0; i < Model.Count; i++)
        {
            var cloth = Model[i];
            <div class="row row-cols-1 @cardSize text-center">
                <div class="col" style="padding: 10px;">
                    <div class="card">
                        @if (cloth.Avatar != null)
                        {
                            <img src="data:image/jpeg;base64,@(Convert.ToBase64String(cloth.Avatar))" />
                        }
                        <div class="card-body">
                            <h5 class="card-title">@cloth.Name</h5>
                            <p class="card-text">@cloth.Description</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Стоимость: @cloth.Price ₽</li>
                        </ul>
                        <div class="card-body">
                            @{
                                var id = cloth.Id;
                            }
                            <a asp-action="Get" asp-route-id="@id" class="card-link">Перейти</a>
                            <hr />
                            <a asp-controller="Basket" asp-action="Add" asp-route-id="@id" class="card-link">Добавить в корзину</a>
                            @if (User.IsInRole("Admin"))
                            {
                                <hr />
                                <a asp-controller="Cloth" asp-action="Delete" asp-route-id="@id" class="btn btn-danger">Удалить</a>   
                                <a asp-controller="Cloth" asp-action="Save" asp-route-id="@id" class="btn btn-primary">Изменить</a>  
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>   
}
<div style="padding: 10px;"></div>
<div class="card col-md-12">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="https://stockmann.ru/upload/medialibrary/559/143294032_886420295441603_5837745517344800140_n.jpg" 
                 class="img-fluid rounded-start rounded" />
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title text-center">Levi’s</h5>
                <p class="card-text" style="font-size: 24px;">
                    Levi Strauss & Co или Levi’s – пожалуй, самый известный американский производитель джинсовой одежды. Бренд  был основан в 1853 году немецким эмигрантом Леви Штраусом. Безусловно, это непотопляемый флагман джинсовой индустрии, на который ориентируются даже модные дома Европы и Азии. Кстати, само понятие «джинсы» стало применяться только в 1960-е годы, когда в таких рабочих штанах фланировали известные звезды, среди которых Мэрилин Манро, Марлон Брандо, Элвис Пресли.
                    В ассортименте культовой  марки многочисленные позиции в стилистике casual или sport: джинсы, рубашки, толстовки, свитеры, куртки, пуховики, рюкзаки, головные уборы. Модели джинсов предназначены мужчинам и женщинам любого возраста: скинни, слим, прямые, клеш, свободные.  
                </p>
            </div>
        </div>
    </div>
</div>
<div style="padding: 10px;"></div>
<div class="card col-md-12">
  <div class="row g-0">
      <div class="col-md-8">
          <div class="card-body">
              <h5 class="card-title text-center">Michael Michael Kors</h5>
              <p class="card-text" style="font-size: 24px;">
                   Американские модные бренды действительно оказались вне конкуренции по многим показателям, включая количество магазинов и финансовые отчеты. Успешный бренд Michael Kors был создан в 1981 году известным дизайнером Майклу Корсу. Специализируется на производстве доступной одежды, обуви, парфюмерии и аксессуаров. Много вещей выполнены в стиле athleisure, для которого характерно сочетание повседневной одежды casual и спортивных вещей. Коллекции бренда каким-то образом подходят практически всем. В этих комфортных вещах можно быть разным, но всегда самим собой.
                   Направление MICHAEL Michael Kors сосредоточено на женских предметах гардероба, обуви и сумках различной вместимости. Компания так активно расширяется, что Michail Kors купили легендарный итальянский бренд Versace и британскую марку обуви Jimmy Choo. Среди поклонников бренда можно увидеть Дженнифер Лопес, Хайди Клум, Рэйчел Макадамс, Кэтрин Зета-Джонс.
              </p>
          </div>
      </div>
          <div class="col-md-4">
              <img src="https://stockmann.ru/upload/medialibrary/007/241301574_1007854830034028_4186590304022296592_n.jpg" 
                   class="img-fluid rounded-start rounded" />
          </div>
  </div>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Магазин</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="https://raw.githack.com/ttskch/select2-bootstrap4-theme/master/dist/select2-bootstrap4.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/backImage.css"/>
    <link rel="stylesheet" href="~/css/menu.css"/>
    <link rel="stylesheet" href="~/css/paragraph.css"/>
    <link rel="stylesheet" href="~/css/card.css"/>
    <link rel="stylesheet" href="~/css/label.css"/>
</head>
<body class="backgroundImage">
<header>
    <nav class="navbar navbar-expand-lg" style="background-color: white;">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index"><span style="color:black; font-family:Impact; font-size:30px; background-color:white; border-radius:10px;">Магазин</span>@*<img src="~/Img/LSKIcon.jpg" style="width:30px; height: 30px; border-radius: 10px;">*@</a>
        <button class="navbar-toggler badge-light" style="border-radius:10px;" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-square-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm4 4a.5.5 0 0 0-.374.832l4 4.5a.5.5 0 0 0 .748 0l4-4.5A.5.5 0 0 0 12 6H4z" />
            </svg>
        </button>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle ParagraphLayout active text-black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-family:'Comic Sans MS'; font-weight: bold;">
                        Аккаунт
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <ul class="nav flex-column ParagraphHome">
                                        @if (!User.Identity.IsAuthenticated)
                                        {
                                            <li class="nav-item text-center">
                                                <a class="nav-link active text-white" asp-controller="Account" asp-action="Register">
                                                    Регистрация
                                                </a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link active text-white" asp-controller="Account" asp-action="Login">
                                                    Вход
                                                </a>
                                            </li>   
                                        }
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link active text-white" asp-controller="Account" asp-action="ChangePassword">
                                                    Смена пароля
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ParagraphLayout active text-black" href="#" data-toggle="dropdown" style="font-family:'Comic Sans MS'; font-weight: bold;">
                            Товары
                        </a>
                        <div class="dropdown-menu">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <ul class="nav flex-column ParagraphHome">
                                            <li class="nav-item text-center">
                                                <a class="nav-link active text-white" asp-controller="Cloth" asp-action="List">
                                                    Список
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>   
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ParagraphLayout active text-black" href="#" data-toggle="dropdown" style="font-family:'Comic Sans MS'; font-weight: bold;">
                            Баланс
                        </a>
                        <div class="dropdown-menu">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <ul class="nav flex-column ParagraphHome">
                                            <li class="nav-item text-center">
                                                <a class="nav-link active text-white" asp-controller="Balance" asp-action="Get">
                                                    Вывод
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>   
                }
                @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin")))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ParagraphLayout active text-black" href="#" data-toggle="dropdown" style="font-family:'Comic Sans MS'; font-weight: bold;">
                            Админ
                        </a>
                        <div class="dropdown-menu">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <ul class="nav flex-column ParagraphHome">
                                            <li class="nav-item text-center">
                                                <a class="nav-link active text-white" asp-controller="Cloth" asp-action="Save">
                                                    Создание
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>   
                }
            </ul>

            @if (User.Identity.IsAuthenticated)
            {
                <form method="post" asp-controller="Account" asp-action="Logout">
                    <input class="btn btn-danger rounded" style="font-family:'Comic Sans MS'; font-weight: bold; font-size:20px;" type="submit" value="Выход" />
                </form>
                
                <a method="post" asp-controller="Basket" asp-action="List" style="padding: 10px;">
                    <input class="btn btn-primary rounded" style="font-family:'Comic Sans MS'; font-weight: bold; font-size:20px;" type="submit" value="Корзина" />
                </a>
            }
        </div>
    </nav>
</header>
<div class="container-fluid col-xl-12">
    <main role="main">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
@await RenderSectionAsync("pageScripts", required: false)
</body>
</html>